---
typora-copy-images-to: img
---

## 异常的体系

![1491277295296](img/1491277295296.png)

异常：是在运行时期发生的不正常情况。 在java中用类的形式对不正常情况进行了描述和封装对象。描述不正常的情况的类，就称为异常类。

1. 以前正常流程代码和问题处理代码相结合，现在将正常流程代码和问题处理代码分离，提高阅读性。
2. 其实异常就是java通过面向对象的思想将问题封装成了对象，用异常类对其进行描述。
3. 不同的问题用不同的类进行具体的描述。比如角标越界、空指针异常等等。
4. 问题很多，意味着描述的类也很多，将其共性进行向上抽取，形成了异常体系。

不正常情况分成了两大类：

Throwable：无论是error，还是异常、问题，问题发生就应该可以抛出，让调用者知道并处理。

该体系的特点就在于Throwable及其所有的子类都具有可抛性。

可抛性到底指的是什么呢？怎么体现可抛性呢？

其实是通过两个关键字来体现的：throws、throw，凡是可以被这两个关键字所操作的类和对象都具备可抛性。

1. 一般不可处理的：Error

   特点：是由jvm抛出的严重性问题。

   这种问题发生，一般不针对性处理，直接修改程序。

2. 可以处理的：Exception

   该体系的特点：子类的后缀名都是用其父类名作为后缀，阅读性很强。

## 常见异常

| 异常                              | 说明      |
| :------------------------------ | :------ |
| IndexOutOfBoundsException       | 角标越界异常  |
| NullPointerException            | 空指针异常   |
| ConcurrentModificationException | 并发修改异常  |
| ClassCastException              | 类型转换异常  |
| UnsupportedOperationException   | 不支持操作异常 |
| NullPointerException            | 没有元素异常  |
| IllegalArgumentException        | 非法参数异常  |
| IllegalAccessException          | 非法的访问异常 |

## Throwable常用方法

| 方法声明                          | 功能描述                               |
| :---------------------------- | :--------------------------------- |
| getMessage()                  | 获取异常信息，返回字符串。                      |
| toString()                    | 获取异常类名和异常信息，返回字符串。                 |
| printStackTrace()             | 获取异常类名和异常信息，以及异常出现在程序中的位置，返回值void。 |
| printStackTrace(PrintStreams) | 通常用该方法将异常内容保存在日志文件中，以便查阅。          |

示例：

```java
class Demo{
   public static int method(int[] arr, int index){
       if(arr == null){
           throw new NullPointerException("数组的引用不能为空！");
       }
       if(index >= arr.length ){
           throw new ArrayIndexOutOfBoundsException("数组的角标越界：" +
                   index);
       }
       return arr[index];
   }
}
class ExceptionDemo{
   public static void main(String[] args){
       int[] arr = new int[3];
       Demo.method(arr,30);
   }
}
```

运行结果：

![1491276104173](img/1491276104173.png)

## 自定义异常

可以自定义出现的问题称为自定义异常。
对于角标为负数的情况，可以用负数角标异常来表示，负数角标这种异常在java中并没有定义过。
那就按照java异常的创建思想，面向对象，将负数角标进行自定义描述，并封装成对象。
这种自定义的问题描述称为自定义异常。

**注意事项：**

如果让一个类成为异常类，必须要继承异常体系，因为只有成为异常体系的子类才有资格具备可抛性，才可以被两个关键字所操作：throws、throw。

自定义类继承Exception或者其子类，通过构造函数定义异常信息。

**示例：**

```java
Class DemoException extends Exception

{
    DemoException(Stringmessage)
    {
        super(message);
    }
}
```

通过throw将自定义异常抛出。

自定义类继承Exception，作为基类

```java
public class HMException extends Exception {

	public HMException() {
		super();
		// TODO Auto-generated constructor stub
	}

	public HMException(String detailMessage, Throwable throwable) {
		super(detailMessage, throwable);
		// TODO Auto-generated constructor stub
	}

	public HMException(String detailMessage) {
		super(detailMessage);
		// TODO Auto-generated constructor stub
	}

	public HMException(Throwable throwable) {
		super(throwable);
		// TODO Auto-generated constructor stub
	}

}
```
子类

```java
public class HMAException extends HMException {

}

public class HMBException extends HMException {

}

public class HMCException extends HMException {

}

public class HMDException extends HMException {

}
```
ExceptionHandler异常处理器

```java
public class ExceptionHandler {
	/**
	 * 根据不同的HMException给用户具体的提示
	 * @param e
	 */
	public static void toastByHMException(Context context, HMException e) {
		int errCode = 0;
		// errCode 具体化
		if (e instanceof HMAException) {
			errCode = 1;
		} else if (e instanceof HMBException) {
			errCode = 2;
		} else if (e instanceof HMCException) {
			errCode = 3;

		} else if (e instanceof HMDException) {
			errCode = 4;
		}
		// 根据不同的errcode给用户做提示
		toastByErrCode(context, errCode);
	}

	private static void toastByErrCode(Context context, int errCode) {
		String content = "";
		switch (errCode) {
		case 1:
			content = "程序出现了HMAException";
			break;
		case 2:
			content = "程序出现了HMBException";
			break;
		case 3:
			content = "程序出现了HMCException";
			break;
		case 4:
			content = "程序出现了HMDException";
			break;

		default:
			break;
		}
		Toast.makeText(context, content, 0).show();
	}
}
```
HMApi

```java
public class HMApi {
	public void method1() throws HMException {
		// 模拟,某一个时刻出现了HMAException
		throw new HMAException();
	}

	public void method2() throws HMException {
		// 模拟,某一个时刻出现了HMBException
		throw new HMBException();
	}

	public void method3() throws HMException {
		// 模拟,某一个时刻出现了HMCException
		throw new HMCException();
	}

	public void method4() throws HMException {
		// 模拟,某一个时刻出现了HMDException
		throw new HMDException();
	}
}
```
MainActivity.class，使用自定义异常

```java
public class MainActivity extends Activity {

	private HMApi	mApi;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);
		mApi = new HMApi();
	}

	public void method1(View v) {
		try {
			mApi.method1();
		} catch (HMException e) {
			e.printStackTrace();
			ExceptionHandler.toastByHMException(MainActivity.this, e);
		}
	}

	public void method2(View v) {
		try {
			mApi.method2();
		} catch (HMException e) {
			e.printStackTrace();
			ExceptionHandler.toastByHMException(MainActivity.this, e);
		}
	}

	public void method3(View v) {
		try {
			mApi.method3();
		} catch (HMException e) {
			e.printStackTrace();
			ExceptionHandler.toastByHMException(MainActivity.this, e);
		}
	}

	public void method4(View v) {
		try {
			mApi.method4();
		} catch (HMException e) {
			e.printStackTrace();
			ExceptionHandler.toastByHMException(MainActivity.this, e);
		}
	}

}
```

## throws和throw的区别

1. throws用于标识函数暴露出的异常类，并且可以抛出多个，用逗号分隔。throw用于抛出异常对象

2. thorws用在函数上，后面跟异常类名。throw用在函数内，后面跟异常对象。

定义功能方法时，需要把出现的问题暴露出来让调用者去处理，那么就通过throws在函数上标识。

在功能方法内部出现某种情况，程序不能继续运行，需要进行跳转时，就用throw把异常对象抛出。

**示例：**

```java
class FuShuIndexException extends Exception {
    FuShuIndexException() {
    }

    FuShuIndexException(String msg) {
        super(msg);
    }
}

class Demo {
    public static int method(int[] arr, int index) throws FuShuIndexException {
        if (index < 0) {
            throw new FuShuIndexException ("数组的角标是负数啦！");
        }
        return arr[index];
    }
}

class ExceptionDemo {
    public static void main(String[] args) throws FuShuIndexException {
        int[] arr = new int[3];
        Demo.method(arr, -30);
    }
}
```

运行结果：

![1491276277598](img/1491276277598.png)

## 异常的分类：
### 编译时被检测异常

只要是Exception和其子类都是，除了特殊子类RuntimeException体系。这种问题一旦出现，希望在编译时就进行检测，让这种问题有对应的处理方式。这样的问题都可以针对性的处理。

### 编译时不检测异常（运行时异常）

就是Exception中的RuntimeException和其子类。这种问题的发生，无法让功能继续，运算无法运行，更多是因为调用的原因导致的或者引发了内部状态的改变导致的。

那么这种问题一般不处理，直接编译通过，在运行时，让调用者调用时的程序强制停止，让调用者对代码进行调整。

所以自定义异常时，要么继承Exception，要么继承RuntimeException。

**示例：**

```java
class FuShuIndexException extends RuntimeException {
    FuShuIndexException() {
    }

    FuShuIndexException(String msg) {
        super(msg);
    }
}

class Demo {
    public static int method(int[] arr, int index) {
        // RuntimeException没有必要用throws抛出，并不是必须要处理
        if (index < 0) {
            throw new FuShuIndexException("数组的角标是负数啦！");
        }
        return arr[index];
    }
}
```

运行结果：

![1491276429985](img/1491276429985.png)

**注意事项：**

RuntimeException是那些可能在Java虚拟机正常运行期间抛出的异常的超类。可能在执行方法期间抛出但未被捕获的RuntimeException的任何子类都无需在throws子句中进行声明。

## 异常处理的捕捉形式

可以对异常进行针对性处理的方式。具体格式是：

```java
    try{
         //需要被检测异常的代码。
    }
    catch(异常类 变量) //该变量用于接收发生的异常对象
    {
         //处理异常的代码。
    }
    finally{
         //一定会执行的代码；
    }
```

**注意事项：**

finally代码块只有一种情况不会被执行，就是在之前执行了System.exit(0)。

**处理过程：**

try 中检测到异常会将异常对象传递给catch，catch捕获到异常进行处理。
finally 里通常用来关闭资源。比如：数据库资源，IO资源等。

需要注意：try是一个独立的代码块，在其中定义的变量只在该变量块中有效。如果在try以外继续使用，需要在try外建立引用，在try中对其进行初始化。IO，Socket就会遇到。

**示例：**

```java
class FuShuIndexException extends RuntimeException{
    FuShuIndexException(){}

    FuShuIndexException(String msg){
        super(msg);
    }
}

class Demo{
    public static int method(int[] arr, int index) throws
            NullPointerException,FuShuIndexException{
        if(arr == null)
            throw new NullPointerException("没有任何数组实体");
        if(index < 0){
            throw new FuShuIndexException("数组的角标是负数啦！");
        }
        return arr[index];
    }
}

class ExceptionDemo{
    public static void main(String[] args){
        int[] arr = new int[3];
        try{
            int num = Demo.method(arr,-30);
            System.out.println("num:" + num);
        } catch(NullPointerException e){
            System.out.println(e);
        } catch(FuShuIndexException e){
            System. out.println("message:" + e.getMessage());
            System.out.println("string:" + e);
            e.printStackTrace(); //jvm 默认的异常处理机制就是调用异常对象的这个方法。
            System.out.println("负数角标异常！！！");
        } catch(Exception e){//Exception的catch放在最下面，先处理有针对性的异常
            System.out.println(e);
        }
        System.out.println("over" );
    }
}
```

运行结果：

![1491276565803](img/1491276565803.png)

## 异常处理的原则

1.  函数内容如果抛出需要检测的异常，那么函数上必须要声明。否则，必须在函数内用try/catch捕捉，否则编译失败。

2. 如果调用到了声明异常的函数，要么try/catch，要么throws，否则编译失败。

3. 什么时候catch，什么时候throws呢？

    功能内容可以解决，用catch。解决不了，用throws告诉调用者，由调用者解决。

4. 一个功能如果抛出了多个异常，那么调用时，必须有对应多个catch进行针对性处理。内部有几个需要检测的异常，就抛几个异常，抛出几个，就catch几个。

示例：

```java
 class Demo{
        public int show(int index) throws ArrayIndexOutOfBoundsException{
              if(index < 0)
                    throw new ArrayIndexOutOfBoundsException("越界啦！");
              int[] arr = new int[3];
              return arr[index];
        }
 }

 class ExceptionDemo{
        public static void main(String[] args){
             Demo d = new Demo();
             try{
                   int num = d.show(-3);
                   System.out.println("num = " + num);
              } catch(ArrayIndexOutOfBoundsException e){
                   System.out.println(e.toString());
                   System.exit(0);//退出jvm
              } finally{//通常用于关闭（释放）资源
                   System.out.println("finally");//由于前面执行了System.exit(0);，故不会执行此语句。
              }
             System.out.println("over");
       }
 }
```

运行结果：

![1491276648860](img/1491276648860.png)

try catch finally 代码块组合特点：

1. try catch finally
2. try catch(多个)：当没有资源需要释放时，可以不用定义finally。
3. try finally：异常无法直接catch处理，但是资源必须关闭。

示例：

```java
 void show() throws Exception{
      try{
           //开启资源
           throw new Exception();
       }finally{
           //关闭资源
       }
 }
```

## 异常综合案例

```java
 /*
 毕老师用电脑上课。

 问题领域中涉及两个对象。
 毕老师，电脑。

 分析其中的问题。
 比如电脑蓝屏，冒烟等。
 */
 class LanPingException extends Exception{
       LanPingException(String msg){
              super(msg);
       }
 }

 class MaoYanException extends Exception{
       MaoYanException(String msg){
              super(msg);
       }
 }

 class NoPlanException extends Exception{
       NoPlanException(String msg){
              super(msg);
       }
 }

 class Computer{
        private int state = 1;//0 2
        public void run() throws LanPingException,MaoYanException{
              if(state == 1)
                    throw new LanPingException("电脑蓝屏啦！");
              if(state == 2)
                    throw new MaoYanException("电脑冒烟啦！");
              System. out.println("电脑运行");
        }
        public void reset(){
             state = 0;
             System.out.println("电脑重启");
        }
 }

 class Teacher{
        private String name ;
        private Computer comp ;

        Teacher(String name){
              this.name = name;
              comp = new Computer();
        }

        public void prelect() throws NoPlanException{
              try{
                   comp.run();
                   System. out.println(name + "讲课");
              } catch(LanPingException e){
                   System.out.println(e.toString());
                   comp.reset();
                   prelect();
              } catch(MaoYanException e){
                   System. out.println(e.toString());
                   test();
                    //可以对电脑进行维修
                    throw new NoPlanException("课时进度无法完成，原因：" + e.getMessage());
              }
        }
        public void test(){
             System.out.println("大家练习");
        }
 }

 class ExceptionDemo{
        public static void main(String[] args){
             Teacher t = new Teacher("毕老师");
              try{
                   t.prelect();
              } catch(NoPlanException e){
                   System.out.println(e.toString() + "......." );
                   System.out.println("换人");
              }
        }
 }
```

运行结果：

![1491276689148](img/1491276689148.png)

## 异常的注意事项    

1. RuntimeException以及其子类如果在函数中被throw抛出，可以不用在函数上声明。
2. 子类在覆盖父类方法时，父类的方法如果抛出了异常，那么子类的方法只能抛出父类的异常或者该异常的子类。
3. 如果父类抛出多个异常，那么子类只能抛出父类异常的子集。

简单说：子类覆盖父类只能抛出父类的异常或者子类的子集。如果父类的方法没有抛出异常，那么子类覆盖时绝对不能抛，就只能try。

## 异常常见问题

**1. try{ }里有一个return x语句，那么紧跟在这个try后的finally { }里的code会不会被执行，什么时候被执行，在return前还是后?**

在return中间执行，return x其实是先执行了返回值计算，并把计算结果的地址保存在一个临时的局部变量中，然后开始执行finally子句，finally执行完毕后，再从先前的临时变量中取得返回地址，返回方法的最终结果。根据这样的处理方式，当我们试图在finally子句中再行改变x的值时，已经不会对方法的返回结果造成影响。

return并不是让函数马上返回，而是return语句执行后，将把返回结果放置进函数栈中，此时函数并不是马上返回，它要执行finally语句后才真正开始返回

**2. 运行时异常runtime exception与一般异常checked exception有何异同？**

对于检查异常，编译器强制要求我们去try catch，否则编译不通过；运行时异常我们可以不处理。这样的异常由虚拟机接管。出现运行时异常后，系统会把异常一直往上层抛，一直遇到处理代码。如果不对运行时异常进行处理，那么出现运行时异常之后，要么是线程中止，要么是主程序终止

异常表示程序运行过程中可能出现的非正常状态，运行时异常表示虚拟机的通常操作中可能遇到的异常，是一种常见运行错误。java编译器要求方法必须声明抛出可能发生的非运行时异常，但是并不要求必须声明抛出未被捕获的运行时异常